const KNOWN_PUBLIC_ASSET_PATHS = new Set([
  'creative-stack/fonts/roc-grotesk/RocGroteskBold/font.woff',
  'creative-stack/fonts/roc-grotesk/RocGroteskBold/font.woff2',
  'creative-stack/fonts/roc-grotesk/RocGroteskMedium/font.woff',
  'creative-stack/fonts/roc-grotesk/RocGroteskMedium/font.woff2',
  'creative-stack/fonts/roc-grotesk/RocGroteskRegular/font.woff',
  'creative-stack/fonts/roc-grotesk/RocGroteskRegular/font.woff2',
  'creative-stack/fonts/roc-grotesk/RocGroteskWideBold/font.woff',
  'creative-stack/fonts/roc-grotesk/RocGroteskWideBold/font.woff2',
  'creative-stack/fonts/roc-grotesk/RocGroteskWideMedium/font.woff',
  'creative-stack/fonts/roc-grotesk/RocGroteskWideMedium/font.woff2',
  'creative-stack/images/kursy/kkz-administrowanie-sieci-komputerowych-i-serwerow.png',
  'creative-stack/images/kursy/kkz-chow-i-inseminacja-zwierzat.png',
  'creative-stack/images/kursy/kkz-fotografia.png',
  'creative-stack/images/kursy/kkz-fryzjerstwo-z-certyfikatem-schwarzkopf-professional.png',
  'creative-stack/images/kursy/kkz-grafika-komputerowa-i-multimedia.png',
  'creative-stack/images/kursy/kkz-kadry-place-i-podatki.png',
  'creative-stack/images/kursy/kkz-kosmetyka.png',
  'creative-stack/images/kursy/kkz-logistyka.png',
  'creative-stack/images/kursy/kkz-pomoc-weterynaryjna.png',
  'creative-stack/images/kursy/kkz-programowanie-i-bazy-danych.png',
  'creative-stack/images/kursy/kkz-projektowanie-i-testowanie-aplikacji.png',
  'creative-stack/images/kursy/kkz-rachunkowosc-z-certyfikatem-insert.png',
  'creative-stack/images/kursy/kkz-stylizacja-fryzur.png',
  'creative-stack/images/kursy/kkz-technik-informatyk.png',
  'creative-stack/images/kursy/kkz-technik-programista.png',
  'creative-stack/images/kursy/kkz-technik-rachunkowosci.png',
  'creative-stack/images/kursy/kkz-technik-weterynarii.png',
  'creative-stack/images/kursy/pku-akademia-sprzedazy-z-wykorzystaniem-sztucznej-inteligencji.png',
  'creative-stack/images/kursy/pku-animacja-3d.png',
  'creative-stack/images/kursy/pku-barber-kurs-intensywny.png',
  'creative-stack/images/kursy/pku-barber.png',
  'creative-stack/images/kursy/pku-dekorowanie-wnetrz-i-home-staging.png',
  'creative-stack/images/kursy/pku-dietetyka-i-zaburzenia-odzywiania.png',
  'creative-stack/images/kursy/pku-dogoterapeuta.png',
  'creative-stack/images/kursy/pku-doula-asystentka-rodzacej.png',
  'creative-stack/images/kursy/pku-ekotechnologia-dla-esg.png',
  'creative-stack/images/kursy/pku-fashion-design-podstawy-projektowania-ubioru.png',
  'creative-stack/images/kursy/pku-finanse-i-rachunkowosc-z-certyfikatem-insert.png',
  'creative-stack/images/kursy/pku-florystyka-i-kompozycje-kwiatowe.png',
  'creative-stack/images/kursy/pku-fotografia-z-certyfikatem-canon.png',
  'creative-stack/images/kursy/pku-grafika-komputerowa.png',
  'creative-stack/images/kursy/pku-groomer-pielegnacja-i-strzyzenie-zwierzat-kurs-intensywny.png',
  'creative-stack/images/kursy/pku-groomer-pielegnacja-i-strzyzenie-zwierzat.png',
  'creative-stack/images/kursy/pku-holistyczna-opieka-nad-zwierzetami-domowymi.png',
  'creative-stack/images/kursy/pku-jezyk-angielski-poziom-podstawowy.png',
  'creative-stack/images/kursy/pku-jezyk-angielski-poziom-srednio-zaawansowany.png',
  'creative-stack/images/kursy/pku-jezyk-niemiecki-poziom-podstawowy.png',
  'creative-stack/images/kursy/pku-jezyk-niemiecki-poziom-srednio-zaawansowany.png',
  'creative-stack/images/kursy/pku-jezyk-polski-poziom-podstawowy.png',
  'creative-stack/images/kursy/pku-jezyk-polski-przygotowanie-do-egzaminu-b1-b2.png',
  'creative-stack/images/kursy/pku-kryminalistyka-z-elementami-kryminologii.png',
  'creative-stack/images/kursy/pku-kurs-survivalowo-strzelecki.png',
  'creative-stack/images/kursy/pku-makijaz-permanentny.png',
  'creative-stack/images/kursy/pku-marketing-internetowy.png',
  'creative-stack/images/kursy/pku-ochrona-danych-osobowych.png',
  'creative-stack/images/kursy/pku-online-abc-biznesu-podstawy-wlasnej-dzialalnosci.png',
  'creative-stack/images/kursy/pku-online-abc-of-business-basic-of-business-activity.png',
  'creative-stack/images/kursy/pku-online-analityk-danych-z-wykorzystaniem-nowoczesnych-technologii.png',
  'creative-stack/images/kursy/pku-online-broker-ubezpieczeniowy.png',
  'creative-stack/images/kursy/pku-online-cyberbezpieczenstwo.png',
  'creative-stack/images/kursy/pku-online-game-design-projektowanie-i-testowanie-gier.png',
  'creative-stack/images/kursy/pku-online-jezyk-hiszpanski-poziom-podstawowy.png',
  'creative-stack/images/kursy/pku-online-jezyk-hiszpanski-poziom-srednio-zaawansowany.png',
  'creative-stack/images/kursy/pku-online-jezyk-migowy.png',
  'creative-stack/images/kursy/pku-online-mlodszy-koder-medyczny.png',
  'creative-stack/images/kursy/pku-online-mykoterapia-zastosowanie-grzybow-leczniczych-w-praktyce.png',
  'creative-stack/images/kursy/pku-online-posrednictwo-nieruchomosci.png',
  'creative-stack/images/kursy/pku-online-sztuczna-inteligencja-i-prompt-engineering.png',
  'creative-stack/images/kursy/pku-online-ux-design.png',
  'creative-stack/images/kursy/pku-opiekun-w-zlobku-lub-klubie-dzieciecym.png',
  'creative-stack/images/kursy/pku-organizator-imprez-slubnych-i-konferencyjnych.png',
  'creative-stack/images/kursy/pku-podologia-z-ortonyksja.png',
  'creative-stack/images/kursy/pku-pomoc-nauczyciela-przedszkola.png',
  'creative-stack/images/kursy/pku-programowanie-aplikacji-internetowych-i-mobilnych.png',
  'creative-stack/images/kursy/pku-programowanie-java.png',
  'creative-stack/images/kursy/pku-programowanie-python-z-cisco-networking-academy.png',
  'creative-stack/images/kursy/pku-projektowanie-ogrodow.png',
  'creative-stack/images/kursy/pku-refleksologia.png',
  'creative-stack/images/kursy/pku-rejestratorka-sekretarka-medyczna.png',
  'creative-stack/images/kursy/pku-specjalista-ds-e-commerce-patronat-salesmanago.png',
  'creative-stack/images/kursy/pku-specjalista-ds-mediow-spolecznosciowych.png',
  'creative-stack/images/kursy/pku-specjalista-ds-spedycji.png',
  'creative-stack/images/kursy/pku-stylizacja-i-pielegnacja-oprawy-oczu.png',
  'creative-stack/images/kursy/pku-stylizacja-paznokci-z-certyfikatem-semilac-professional.png',
  'creative-stack/images/kursy/pku-szkolenia-i-behawiorystyka-zwierzat.png',
  'creative-stack/images/kursy/pku-tatuazysta-kurs-intensywny.png',
  'creative-stack/images/kursy/pku-tatuazysta.png',
  'creative-stack/images/kursy/pku-terapia-tkanek-miekkich.png',
  'creative-stack/images/kursy/pku-trener-personalny.png',
  'creative-stack/images/kursy/pku-trychologia.png',
  'creative-stack/images/kursy/pku-wizaz-i-stylizacja.png',
  'creative-stack/images/kursy/pku-ziololecznictwo.png',
  'creative-stack/images/kursy/pku-zoofizjoterapeuta-zwierzat-towarzyszacych.png',
  'creative-stack/images/medyczne/sp-asystent-osoby-niepelnosprawnej.png',
  'creative-stack/images/medyczne/sp-asystentka-stomatologiczna-z-elementami-implantologii.png',
  'creative-stack/images/medyczne/sp-higienistka-stomatologiczna.png',
  'creative-stack/images/medyczne/sp-opiekun-medyczny.png',
  'creative-stack/images/medyczne/sp-ortoptystka-rehabilitacja-wzroku.png',
  'creative-stack/images/medyczne/sp-protetyk-sluchu.png',
  'creative-stack/images/medyczne/sp-technik-dentystyczny-z-technologia-cad-cam.png',
  'creative-stack/images/medyczne/sp-technik-elektroniki-i-informatyki-medycznej.png',
  'creative-stack/images/medyczne/sp-technik-elektroradiolog.png',
  'creative-stack/images/medyczne/sp-technik-farmaceutyczny.png',
  'creative-stack/images/medyczne/sp-technik-masazysta-z-elementami-fizjoterapii.png',
  'creative-stack/images/medyczne/sp-technik-ortopeda.png',
  'creative-stack/images/medyczne/sp-technik-sterylizacji-medycznej.png',
  'creative-stack/images/medyczne/sp-terapeuta-zajeciowy-z-elementami-dogoterapii.png',
  'creative-stack/images/medyczne/sp-terapia-zajeciowa-z-florystyka.png',
  'creative-stack/images/policealne/sp-kosmetyka-estetyczna.png',
  'creative-stack/images/policealne/sp-opiekun-osoby-starszej.png',
  'creative-stack/images/policealne/sp-opiekun-w-domu-pomocy-spolecznej.png',
  'creative-stack/images/policealne/sp-opiekunka-dziecieca-z-masazem-shantala.png',
  'creative-stack/images/policealne/sp-podolog.png',
  'creative-stack/images/policealne/sp-produkcji-filmowa-i-telewizyjna.png',
  'creative-stack/images/policealne/sp-technik-administracji-zarzadzanie-biurem.png',
  'creative-stack/images/policealne/sp-technik-bhp.png',
  'creative-stack/images/policealne/sp-technik-realizacji-nagran.png',
  'creative-stack/images/policealne/sp-technik-uslug-kosmetycznych-z-certyfikatem-bielenda-professional.png',
  'creative-stack/logos/partners/3shape.svg',
  'creative-stack/logos/partners/bego.svg',
  'creative-stack/logos/partners/bielenda-professional.svg',
  'creative-stack/logos/partners/canon.svg',
  'creative-stack/logos/partners/cisco.svg',
  'creative-stack/logos/partners/colgate.svg',
  'creative-stack/logos/partners/denon-dental.svg',
  'creative-stack/logos/partners/dietetykpro.svg',
  'creative-stack/logos/partners/ecolab.svg',
  'creative-stack/logos/partners/fagron.svg',
  'creative-stack/logos/partners/farmona.svg',
  'creative-stack/logos/partners/gameup.svg',
  'creative-stack/logos/partners/gemini-polska.svg',
  'creative-stack/logos/partners/habys.svg',
  'creative-stack/logos/partners/inglot.svg',
  'creative-stack/logos/partners/insert.svg',
  'creative-stack/logos/partners/intel.svg',
  'creative-stack/logos/partners/interton-gn.svg',
  'creative-stack/logos/partners/kamsoft.svg',
  'creative-stack/logos/partners/kind.svg',
  'creative-stack/logos/partners/kryolan.svg',
  'creative-stack/logos/partners/microsoft.svg',
  'creative-stack/logos/partners/morebananas.svg',
  'creative-stack/logos/partners/msi.svg',
  'creative-stack/logos/partners/oral-b.svg',
  'creative-stack/logos/partners/podopharm.svg',
  'creative-stack/logos/partners/progrupa.svg',
  'creative-stack/logos/partners/promedica-24.svg',
  'creative-stack/logos/partners/protefix.svg',
  'creative-stack/logos/partners/salesmanago.svg',
  'creative-stack/logos/partners/schwarzkopf-professional.svg',
  'creative-stack/logos/partners/semilac-professional.svg',
  'creative-stack/logos/partners/vita.svg',
  'creative-stack/logos/partners/webmetric.svg',
  'creative-stack/logos/partners/zabka.svg',
  'creative-stack/logos/teb-edukacja.svg',
  'creative-stack/logos/teb-kursy.svg',
  'creative-stack/logos/teb-medyczne.svg',
  'creative-stack/logos/teb-policealne.svg',
]);

function normalizePublicAssetPath(path: string): string {
  const baseUrl = import.meta.env.BASE_URL || '/';
  const normalizedBase = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;

  let normalizedPath = path.trim().replace(/\\/g, '/');

  if (normalizedPath.startsWith(normalizedBase)) {
    normalizedPath = normalizedPath.slice(normalizedBase.length);
  }

  return normalizedPath.startsWith('/')
    ? normalizedPath.slice(1)
    : normalizedPath;
}

export function publicAssetExists(path: string | undefined): boolean {
  if (!path) {
    return false;
  }

  const normalizedPath = path.trim();

  if (
    normalizedPath.startsWith('http://') ||
    normalizedPath.startsWith('https://') ||
    normalizedPath.startsWith('data:')
  ) {
    return true;
  }

  return KNOWN_PUBLIC_ASSET_PATHS.has(normalizePublicAssetPath(normalizedPath));
}
